[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
upload_protocol = esptool

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio

monitor_speed = 115200

check_tool = clangtidy
check_skip_packages = yes

build_flags =
    -D CONFIG_FREERTOS_USE_TRACE_FACILITY=1
    -D INCLUDE_uxTaskGetSystemState=1
    -D CONFIG_FREERTOS_RUN_TIME_STATS=1
    -D CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
    -D CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1

lib_extra_dirs =
    ../SharedComponents/Drivers
    ../SharedComponents/Tasks
    ../SharedComponents/Messages
    ../SharedComponents/Services
    ../SharedComponents/Net
    ../SharedComponents/Data
    ../SharedComponents/Log
